---
name: Artifacts

on:
  push:
    branches:
      - chad
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |-
          make build
